# postgres volume problem: https://stackoverflow.com/questions/64973111/how-to-mount-a-docker-volume-in-azure-with-docker-compose-yaml
version: '3.8'

services:
  db:
    container_name: db
    image: postgres:13-alpine
    # ports:
    #   - "5432:5432"
    # volumes:
    #   - postgresdata_prod:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  web:
    container_name: web
    image: registry.hub.docker.com/sophietruong92/quick-read-flaskapp:1.4
    command: gunicorn --bind 0.0.0.0:5050 --log-level debug --timeout 150 --threads=2 manage:app 
    expose:
      - 5050
    deploy:
      resources:
        reservations:
          cpus: '1.5'
          memory: 10G  
    env_file:
      - ./.env.prod
    # volumes:
    #   - appdata:/home/app/web/.cache
    depends_on:
      - db
  nginx:
    container_name: server
    image: registry.hub.docker.com/sophietruong92/quick-read-webserver:1.2
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
# networks:
#   default:
# volumes:
#   postgresdata_prod:
#   appdata: