version: '3.8'

services:
  nginx:
    build: ./services/nginx
    ports:
      - 1337:80
    depends_on:
      - web
  web:
    build: 
      context: ./services/flaskapp
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:8080 manage:app
    expose:
      - 8080
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

volumes:
  postgres_data_prod: